plugins {
	id 'net.neoforged.moddev' version '2.0.144'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

neoForge {
	version = project.neo_version

	runs {
		client {
			client()
		}
		server {
			server()
		}
	}

	mods {
		lifeessentials {
			sourceSet(sourceSets.main)
		}
	}
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}" }
	}
}
