# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# make sure Gradle's toolchain finds the Homebrew JDK 21
org.gradle.java.installations.paths=/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home

# Versions
minecraft_version=1.21.1
neo_version=21.1.248

# Mod Properties
mod_version=1.3.1
maven_group=com.lifeessentials
archives_base_name=life-essentials
